export const UPDATE_SLIDER_COLOR = 'UPDATE_SLIDER_COLOR';
export const UPDATE_PICKER_COLOR = 'UPDATE_PICKER_COLOR';
export const UPDATE_SELECTED_STOP = 'UPDATE_SELECTED_STOP';
export const UPDATE_GRADIENT_TYPE = 'UPDATE_GRADIENT_TYPE';
export const UPDATE_GRADIENT_DIRECTION = 'UPDATE_GRADIENT_DIRECTION';
export const UPDATE_HEX_VALUE = 'UPDATE_HEX_VALUE';

export const INIT_GRADIENTS = 'INIT_GRADIENTS';
export const ADD_GRADIENT = 'ADD_GRADIENT';
export const UPDATE_GRADIENT = 'UPDATE_GRADIENT';
export const DELETE_GRADIENT = 'DELETE_GRADIENT';
